name: Build 2203o
on: 
  repository_dispatch:
  workflow_dispatch:
env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-22.03
  CONFIG_FILE: 2203o.config
  DIY_SH: custom.sh
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: 检查
      uses: actions/checkout@main
    - name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential gawk gcc-multilib flex git gettext libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev
        sudo -E apt-get -y autoremove
        sudo -E apt-get autoclean
    - name: 克隆源代码
      run: |
        df -hT $PWD
        git clone -b openwrt-22.03 --single-branch https://github.com/openwrt/openwrt.git openwrt
        cd openwrt
        git clone -b openwrt-22.03 --single-branch https://github.com/openwrt/luci.git luci
    - name: 更新安装源
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: 自定义配置文件
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_SH
    - name: 下载包文件
      run: |
        cd openwrt
        make defconfig
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: 编译固件
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) V=s
    - name: 上传固件
      uses: actions/upload-artifact@main
      with:
        name: 2203o
        path: openwrt/bin
    - name: 删除任务
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 3
        keep_minimum_runs: 1
