name: Build ax6000v

on: 
  repository_dispatch:
  workflow_dispatch:
#  schedule:
#    - cron: 17 1 * * 2
env:
  CONFIG_FILE: ax6000v.config
  CUSTOM_SH: custom.sh

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync unzip zlib1g-dev file wget
        sudo -E apt-get -y autoremove
        sudo -E apt-get autoclean

    - name: Clone source code
      run: |
        git clone -b main --single-branch https://github.com/openwrt/openwrt.git openwrt

    - name: Update Install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configuration Customization
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $CUSTOM_SH
        cd openwrt
        $GITHUB_WORKSPACE/$CUSTOM_SH

    - name: Download package
      run: |
        cd openwrt
        make defconfig
        make download

    - name: Build firmware
      run: |
        cd openwrt
        make -j1

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ax6000v7
        path: openwrt/bin
